#title = "Http Toml"

[http]
host = "127.0.0.1:8081"

[mysql]
host = "127.0.0.1"
port = "3306"
user = "root"
pass_wd = ""
db = "seckill"

[etcd]
host = "127.0.0.1:2379"
product_key = "sec_kill_product"
